# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Calculator")
        MainWindow.resize(314, 401)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet(" background-color:rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridWidget.setGeometry(QtCore.QRect(10, 10, 291, 371))
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.clear_btn = QtWidgets.QPushButton(self.gridWidget)
        self.clear_btn.setStyleSheet(
            "QPushButton {\n"
            "    background-color: rgb(0, 0, 0);  /* Blue color */\n"
            "    color:rgb(99, 148, 255);  /* White text */\n"
            "    border-radius: 10px;\n"
            "    padding: 5px;\n"
            "    font-size: 28px;\n"
            "    border: 2px solid rgb(0, 85, 255);\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(34, 34, 34)/* Darker blue on hover */\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: rgb(0, 98, 255) /* Even darker blue when clicked */\n"
            "}\n"
            ""
        )
        self.clear_btn.setObjectName("clear_btn")
        self.gridLayout.addWidget(self.clear_btn, 1, 0, 1, 1)
        self.btn_minus = QtWidgets.QPushButton(self.gridWidget)
        self.btn_minus.setStyleSheet(
            "QPushButton {\n"
            "    background-color: rgb(0, 0, 0);  /* Blue color */\n"
            "    color: rgb(255, 255, 255);  /* White text */\n"
            "    border-radius: 10px;\n"
            "    padding: 5px;\n"
            "    font-size: 28px;\n"
            "    border: 2px solid rgb(86, 86, 86);\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(34, 34, 34)/* Darker blue on hover */\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: rgb(0, 98, 255) /* Even darker blue when clicked */\n"
            "}\n"
            ""
        )
        self.btn_minus.setObjectName("btn_minus")
        self.gridLayout.addWidget(self.btn_minus, 1, 2, 1, 1)
        self.btn_x_2 = QtWidgets.QPushButton(self.gridWidget)
        self.btn_x_2.setStyleSheet(
            "QPushButton {\n"
            "    background-color: rgb(0, 0, 0);  /* Blue color */\n"
            "    color: rgb(255, 255, 255);  /* White text */\n"
            "    border-radius: 10px;\n"
            "    padding: 5px;\n"
            "    font-size: 28px;\n"
            "    border: 2px solid rgb(86, 86, 86);\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(34, 34, 34)/* Darker blue on hover */\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: rgb(0, 98, 255) /* Even darker blue when clicked */\n"
            "}\n"
            ""
        )
        self.btn_x_2.setObjectName("btn_x_2")
        self.gridLayout.addWidget(self.btn_x_2, 1, 3, 1, 1)
        self.display_1 = QtWidgets.QLabel(self.gridWidget)
        self.display_1.setEnabled(True)
        self.display_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.display_1.setAutoFillBackground(False)
        self.display_1.setStyleSheet(
            'font: 63 14pt "Yu Gothic UI Semibold";\n'
            " background-color: rgb(255, 255, 255)\n"
            ""
        )
        self.display_1.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.display_1.setObjectName("display_1")
        self.gridLayout.addWidget(self.display_1, 0, 0, 1, 4)
        self.btn1 = QtWidgets.QPushButton(self.gridWidget)
        self.btn1.setStyleSheet(
            "QPushButton {\n"
            "    background-color: rgb(0, 0, 0);  /* Blue color */\n"
            "    color: rgb(255, 255, 255);  /* White text */\n"
            "    border-radius: 10px;\n"
            "    padding: 5px;\n"
            "    font-size: 28px;\n"
            "    border: 2px solid rgb(86, 86, 86);\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(34, 34, 34)/* Darker blue on hover */\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: rgb(0, 98, 255) /* Even darker blue when clicked */\n"
            "}\n"
            ""
        )
        self.btn1.setObjectName("btn1")
        self.gridLayout.addWidget(self.btn1, 2, 0, 1, 1)
        self.btn_plus = QtWidgets.QPushButton(self.gridWidget)
        self.btn_plus.setStyleSheet(
            "QPushButton {\n"
            "    background-color: rgb(0, 0, 0);  /* Blue color */\n"
            "    color: rgb(255, 255, 255);  /* White text */\n"
            "    border-radius: 10px;\n"
            "    padding: 5px;\n"
            "    font-size: 28px;\n"
            "    border: 2px solid rgb(86, 86, 86);\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(34, 34, 34)/* Darker blue on hover */\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: rgb(0, 98, 255) /* Even darker blue when clicked */\n"
            "}\n"
            ""
        )
        self.btn_plus.setObjectName("btn_plus")
        self.gridLayout.addWidget(self.btn_plus, 1, 1, 1, 1)
        self.eqal_btn = QtWidgets.QPushButton(self.gridWidget)
        self.eqal_btn.setBaseSize(QtCore.QSize(22, 0))
        self.eqal_btn.setStyleSheet(
            "QPushButton {\n"
            "    background-color: rgb(0, 0, 0);  /* Blue color */\n"
            "    color: rgb(0, 255, 0);  /* White text */\n"
            "    border-radius: 10px;\n"
            "    padding: 5px;\n"
            "    font-size: 28px;\n"
            "    border: 2px solid rgb(0, 255, 0);\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(34, 34, 34)/* Darker blue on hover */\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: rgb(0, 98, 255) /* Even darker blue when clicked */\n"
            "}\n"
            ""
        )
        self.eqal_btn.setIconSize(QtCore.QSize(55, 55))
        self.eqal_btn.setObjectName("eqal_btn")
        self.gridLayout.addWidget(self.eqal_btn, 6, 3, 1, 1)
        self.btn4 = QtWidgets.QPushButton(self.gridWidget)
        self.btn4.setStyleSheet(
            "QPushButton {\n"
            "    background-color: rgb(0, 0, 0);  /* Blue color */\n"
            "    color: rgb(255, 255, 255);  /* White text */\n"
            "    border-radius: 10px;\n"
            "    padding: 5px;\n"
            "    font-size: 28px;\n"
            "    border: 2px solid rgb(86, 86, 86);\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(34, 34, 34)/* Darker blue on hover */\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: rgb(0, 98, 255) /* Even darker blue when clicked */\n"
            "}\n"
            ""
        )
        self.btn4.setObjectName("btn4")
        self.gridLayout.addWidget(self.btn4, 3, 0, 1, 1)
        self.btn_2 = QtWidgets.QPushButton(self.gridWidget)
        self.btn_2.setStyleSheet(
            "QPushButton {\n"
            "    background-color: rgb(0, 0, 0);  /* Blue color */\n"
            "    color: rgb(255, 255, 255);  /* White text */\n"
            "    border-radius: 10px;\n"
            "    padding: 5px;\n"
            "    font-size: 28px;\n"
            "    border: 2px solid rgb(86, 86, 86);\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(34, 34, 34)/* Darker blue on hover */\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: rgb(0, 98, 255) /* Even darker blue when clicked */\n"
            "}\n"
            ""
        )
        self.btn_2.setObjectName("btn_2")
        self.gridLayout.addWidget(self.btn_2, 2, 1, 1, 1)
        self.btn0 = QtWidgets.QPushButton(self.gridWidget)
        self.btn0.setStyleSheet(
            "QPushButton {\n"
            "    background-color: rgb(0, 0, 0);  /* Blue color */\n"
            "    color: rgb(255, 255, 255);  /* White text */\n"
            "    border-radius: 10px;\n"
            "    padding: 5px;\n"
            "    font-size: 28px;\n"
            "    border: 2px solid rgb(86, 86, 86);\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(34, 34, 34)/* Darker blue on hover */\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: rgb(0, 98, 255) /* Even darker blue when clicked */\n"
            "}\n"
            ""
        )
        self.btn0.setObjectName("btn0")
        self.gridLayout.addWidget(self.btn0, 6, 0, 1, 3)
        self.btn_x = QtWidgets.QPushButton(self.gridWidget)
        self.btn_x.setStyleSheet(
            "QPushButton {\n"
            "    background-color: rgb(0, 0, 0);  /* Blue color */\n"
            "    color: rgb(255, 255, 255);  /* White text */\n"
            "    border-radius: 10px;\n"
            "    padding: 5px;\n"
            "    font-size: 28px;\n"
            "    border: 2px solid rgb(86, 86, 86);\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(34, 34, 34)/* Darker blue on hover */\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: rgb(0, 98, 255) /* Even darker blue when clicked */\n"
            "}\n"
            ""
        )
        self.btn_x.setObjectName("btn_x")
        self.gridLayout.addWidget(self.btn_x, 2, 3, 1, 1)
        self.btn3 = QtWidgets.QPushButton(self.gridWidget)
        self.btn3.setStyleSheet(
            "QPushButton {\n"
            "    background-color: rgb(0, 0, 0);  /* Blue color */\n"
            "    color: rgb(255, 255, 255);  /* White text */\n"
            "    border-radius: 10px;\n"
            "    padding: 5px;\n"
            "    font-size: 28px;\n"
            "    border: 2px solid rgb(86, 86, 86);\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(34, 34, 34)/* Darker blue on hover */\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: rgb(0, 98, 255) /* Even darker blue when clicked */\n"
            "}\n"
            ""
        )
        self.btn3.setObjectName("btn3")
        self.gridLayout.addWidget(self.btn3, 2, 2, 1, 1)
        self.btn6 = QtWidgets.QPushButton(self.gridWidget)
        self.btn6.setStyleSheet(
            "QPushButton {\n"
            "    background-color: rgb(0, 0, 0);  /* Blue color */\n"
            "    color: rgb(255, 255, 255);  /* White text */\n"
            "    border-radius: 10px;\n"
            "    padding: 5px;\n"
            "    font-size: 28px;\n"
            "    border: 2px solid rgb(86, 86, 86);\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(34, 34, 34)/* Darker blue on hover */\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: rgb(0, 98, 255) /* Even darker blue when clicked */\n"
            "}\n"
            ""
        )
        self.btn6.setObjectName("btn6")
        self.gridLayout.addWidget(self.btn6, 3, 2, 1, 1)
        self.btn9 = QtWidgets.QPushButton(self.gridWidget)
        self.btn9.setStyleSheet(
            "QPushButton {\n"
            "    background-color: rgb(0, 0, 0);  /* Blue color */\n"
            "    color: rgb(255, 255, 255);  /* White text */\n"
            "    border-radius: 10px;\n"
            "    padding: 5px;\n"
            "    font-size: 28px;\n"
            "    border: 2px solid rgb(86, 86, 86);\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(34, 34, 34)/* Darker blue on hover */\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: rgb(0, 98, 255) /* Even darker blue when clicked */\n"
            "}\n"
            ""
        )
        self.btn9.setObjectName("btn9")
        self.gridLayout.addWidget(self.btn9, 5, 2, 1, 1)
        self.btn_ac = QtWidgets.QPushButton(self.gridWidget)
        self.btn_ac.setStyleSheet(
            "QPushButton {\n"
            "    background-color: rgb(0, 0, 0);  /* Blue color */\n"
            "    color: rgb(159, 0, 0);  /* White text */\n"
            "    border-radius: 10px;\n"
            "    padding: 5px;\n"
            "    font-size: 28px;\n"
            "    border: 2px solid rgb(198, 0, 0);\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(34, 34, 34)/* Darker blue on hover */\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: rgb(0, 98, 255) /* Even darker blue when clicked */\n"
            "}\n"
            ""
        )
        self.btn_ac.setObjectName("btn_ac")
        self.gridLayout.addWidget(self.btn_ac, 5, 3, 1, 1)
        self.btn5 = QtWidgets.QPushButton(self.gridWidget)
        self.btn5.setStyleSheet(
            "QPushButton {\n"
            "    background-color: rgb(0, 0, 0);  /* Blue color */\n"
            "    color: rgb(255, 255, 255);  /* White text */\n"
            "    border-radius: 10px;\n"
            "    padding: 5px;\n"
            "    font-size: 28px;\n"
            "    border: 2px solid rgb(86, 86, 86);\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(34, 34, 34)/* Darker blue on hover */\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: rgb(0, 98, 255) /* Even darker blue when clicked */\n"
            "}\n"
            ""
        )
        self.btn5.setObjectName("btn5")
        self.gridLayout.addWidget(self.btn5, 3, 1, 1, 1)
        self.btn7 = QtWidgets.QPushButton(self.gridWidget)
        self.btn7.setStyleSheet(
            "QPushButton {\n"
            "    background-color: rgb(0, 0, 0);  /* Blue color */\n"
            "    color: rgb(255, 255, 255);  /* White text */\n"
            "    border-radius: 10px;\n"
            "    padding: 5px;\n"
            "    font-size: 28px;\n"
            "    border: 2px solid rgb(86, 86, 86);\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(34, 34, 34)/* Darker blue on hover */\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: rgb(0, 98, 255) /* Even darker blue when clicked */\n"
            "}\n"
            ""
        )
        self.btn7.setObjectName("btn7")
        self.gridLayout.addWidget(self.btn7, 5, 0, 1, 1)
        self.btn8 = QtWidgets.QPushButton(self.gridWidget)
        self.btn8.setStyleSheet(
            "QPushButton {\n"
            "    background-color: rgb(0, 0, 0);  /* Blue color */\n"
            "    color: rgb(255, 255, 255);  /* White text */\n"
            "    border-radius: 10px;\n"
            "    padding: 5px;\n"
            "    font-size: 28px;\n"
            "    border: 2px solid rgb(86, 86, 86);\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(34, 34, 34)/* Darker blue on hover */\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: rgb(0, 98, 255) /* Even darker blue when clicked */\n"
            "}\n"
            ""
        )
        self.btn8.setObjectName("btn8")
        self.gridLayout.addWidget(self.btn8, 5, 1, 1, 1)
        self.btn_div = QtWidgets.QPushButton(self.gridWidget)
        self.btn_div.setStyleSheet(
            "QPushButton {\n"
            "    background-color: rgb(0, 0, 0);  /* Blue color */\n"
            "    color: rgb(255, 255, 255);  /* White text */\n"
            "    border-radius: 10px;\n"
            "    padding: 5px;\n"
            "    font-size: 28px;\n"
            "    border: 2px solid rgb(86, 86, 86);\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(34, 34, 34)/* Darker blue on hover */\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: rgb(0, 98, 255) /* Even darker blue when clicked */\n"
            "}\n"
            ""
        )
        self.btn_div.setObjectName("btn_div")
        self.gridLayout.addWidget(self.btn_div, 3, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 314, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btn0.clicked.connect(self.b0)
        self.btn1.clicked.connect(self.b1)
        self.btn_2.clicked.connect(self.b2)
        self.btn3.clicked.connect(self.b3)
        self.btn4.clicked.connect(self.b4)
        self.btn5.clicked.connect(self.b5)
        self.btn6.clicked.connect(self.b6)
        self.btn7.clicked.connect(self.b7)
        self.btn8.clicked.connect(self.b8)
        self.btn9.clicked.connect(self.b9)
        self.clear_btn.clicked.connect(self.clear)
        self.btn_ac.clicked.connect(self.a_c)

        self.btn_plus.clicked.connect(self.add)
        self.eqal_btn.clicked.connect(self.eqala)
        self.btn_div.clicked.connect(self.div)
        self.btn_minus.clicked.connect(self.minus)
        self.btn_x.clicked.connect(self.mul)
        self.btn_x_2.clicked.connect(self.m)

    
    txt_leb = ''
    def b0(self):
        self.txt_leb=self.txt_leb +'0'
        self.display_1.setText(self.txt_leb)
        print("0")

    def b1(self):
        if self.txt_leb == '0':
            self.txt_leb= ''
        self.txt_leb=self.txt_leb+'1'
        self.display_1.setText(self.txt_leb)
        print("1")

    def b2(self):
        if self.txt_leb == '0':
            self.txt_leb= ''
        self.txt_leb=self.txt_leb+'2'
        self.display_1.setText(self.txt_leb)
        print("2")
    def b3(self):
        if self.txt_leb == '0':
            self.txt_leb= ''
        self.txt_leb=self.txt_leb+'3'
        self.display_1.setText(self.txt_leb)
        print("3")
    def b4(self):
        if self.txt_leb == '0':
            self.txt_leb= ''
        self.txt_leb=self.txt_leb+'4'
        self.display_1.setText(self.txt_leb)
        print("4")
    def b5(self):
        if self.txt_leb == '0':
            self.txt_leb= ''
        self.txt_leb=self.txt_leb+'5'
        self.display_1.setText(self.txt_leb)
        print("5")
    def b6(self):
        if self.txt_leb == '0':
            self.txt_leb= ''
        self.txt_leb=self.txt_leb+'6'
        self.display_1.setText(self.txt_leb)
        print("6")
    def b7(self):
        if self.txt_leb == '0':
            self.txt_leb= ''
        self.txt_leb=self.txt_leb+'7'
        self.display_1.setText(self.txt_leb)
        print("7")
    def b8(self):
        if self.txt_leb == '0':
            self.txt_leb= ''
        self.txt_leb=self.txt_leb+'8'
        self.display_1.setText(self.txt_leb)
        print("8")
    def b9(self):
        if self.txt_leb == '0':
            self.txt_leb= ''
        self.txt_leb=self.txt_leb+'9'
        self.display_1.setText(self.txt_leb)
        print("9")
    def clear(self):
        if self.txt_leb != '':
            self.txt_leb=self.txt_leb[:-1:]
            self.display_1.setText(self.txt_leb)
            print("clear")
        if self.txt_leb == '':
            self.txt_leb=self.txt_leb + '0'
            self.display_1.setText(self.txt_leb)

    def a_c(self):
        self.txt_leb='0'
        self.display_1.setText(self.txt_leb)
        print("a_c")
    prev_text = ''
    op= ''

    def add(self):
        self.prev_text =self.txt_leb
        self.txt_leb= ''
        if self.txt_leb != '0':
            self.txt_leb= ''
        self.display_1.setText("+")
        self.op ='+'
    def mul(self):
        self.prev_text =self.txt_leb
        self.txt_leb= ''
        if self.txt_leb != '0':
            self.txt_leb= ''
        self.display_1.setText("x")
        self.op ='x'
    def div(self):
        self.prev_text =self.txt_leb
        self.txt_leb= ''
        if self.txt_leb != '0':
            self.txt_leb= ''
        self.display_1.setText("/")
        self.op ='/'
    def minus(self):
        self.prev_text =self.txt_leb
        self.txt_leb= ''
        if self.txt_leb != '0':
            self.txt_leb= ''
        self.display_1.setText("-")
        self.op ='-'


    def eqala(self):
        a = float(self.prev_text) 
        if self.op != '':
            if self.op == '+':
                k = a + float(self.txt_leb)
                self.display_1.setText(str(k))
                self.txt_leb = str(k)
            elif self.op == '-':
                k = a - float(self.txt_leb)
                self.display_1.setText(str(k))
                self.txt_leb = str(k)
            elif self.op == '/':
                k = a / float(self.txt_leb)
                self.display_1.setText(str(k))
                self.txt_leb = str(k)
            elif self.op == 'x':
                k = a * float(self.txt_leb)
                self.display_1.setText(str(k))
                self.txt_leb = str(k)



    def m(self):
        self.op =''
        self.prev_text = '' 
        self.txt_leb = ''
        self.display_1.setText("ki jonoo tipay chis sala")




    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.clear_btn.setToolTip(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><span style=" font-weight:600; font-style:italic; text-decoration: underline; color:#ffffff;">fdasdfasf</span></p></body></html>',
            )
        )
        self.clear_btn.setText(_translate("MainWindow", "C"))
        self.btn_minus.setToolTip(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><span style=" font-weight:600; font-style:italic; text-decoration: underline; color:#ffffff;">fdasdfasf</span></p></body></html>',
            )
        )
        self.btn_minus.setText(_translate("MainWindow", "-"))
        self.btn_x_2.setToolTip(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><span style=" font-weight:600; font-style:italic; text-decoration: underline; color:#ffffff;">fdasdfasf</span></p></body></html>',
            )
        )
        self.btn_x_2.setText(_translate("MainWindow", "h"))
        self.display_1.setText(_translate("MainWindow", "0"))
        self.btn1.setToolTip(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><span style=" font-weight:600; font-style:italic; text-decoration: underline; color:#ffffff;">fdasdfasf</span></p></body></html>',
            )
        )
        self.btn1.setText(_translate("MainWindow", "1"))
        self.btn_plus.setToolTip(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><span style=" font-weight:600; font-style:italic; text-decoration: underline; color:#ffffff;">fdasdfasf</span></p></body></html>',
            )
        )
        self.btn_plus.setText(_translate("MainWindow", "+"))
        self.eqal_btn.setToolTip(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><span style=" font-weight:600; font-style:italic; text-decoration: underline; color:#ffffff;">fdasdfasf</span></p></body></html>',
            )
        )
        self.eqal_btn.setText(_translate("MainWindow", "="))
        self.eqal_btn.setShortcut(_translate("MainWindow", "="))
        self.btn4.setToolTip(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><span style=" font-weight:600; font-style:italic; text-decoration: underline; color:#ffffff;">fdasdfasf</span></p></body></html>',
            )
        )
        self.btn4.setText(_translate("MainWindow", "4"))
        self.btn_2.setToolTip(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><span style=" font-weight:600; font-style:italic; text-decoration: underline; color:#ffffff;">fdasdfasf</span></p></body></html>',
            )
        )
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn0.setToolTip(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><span style=" font-weight:600; font-style:italic; text-decoration: underline; color:#ffffff;">fdasdfasf</span></p></body></html>',
            )
        )
        self.btn0.setText(_translate("MainWindow", "0"))
        self.btn_x.setToolTip(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><span style=" font-weight:600; font-style:italic; text-decoration: underline; color:#ffffff;">fdasdfasf</span></p></body></html>',
            )
        )
        self.btn_x.setText(_translate("MainWindow", "x"))
        self.btn3.setToolTip(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><span style=" font-weight:600; font-style:italic; text-decoration: underline; color:#ffffff;">fdasdfasf</span></p></body></html>',
            )
        )
        self.btn3.setText(_translate("MainWindow", "3"))
        self.btn6.setToolTip(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><span style=" font-weight:600; font-style:italic; text-decoration: underline; color:#ffffff;">fdasdfasf</span></p></body></html>',
            )
        )
        self.btn6.setText(_translate("MainWindow", "6"))
        self.btn9.setToolTip(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><span style=" font-weight:600; font-style:italic; text-decoration: underline; color:#ffffff;">fdasdfasf</span></p></body></html>',
            )
        )
        self.btn9.setText(_translate("MainWindow", "9"))
        self.btn_ac.setToolTip(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><span style=" font-weight:600; font-style:italic; text-decoration: underline; color:#ffffff;">fdasdfasf</span></p></body></html>',
            )
        )
        self.btn_ac.setText(_translate("MainWindow", "AC"))
        self.btn5.setToolTip(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><span style=" font-weight:600; font-style:italic; text-decoration: underline; color:#ffffff;">fdasdfasf</span></p></body></html>',
            )
        )
        self.btn5.setText(_translate("MainWindow", "5"))
        self.btn7.setToolTip(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><span style=" font-weight:600; font-style:italic; text-decoration: underline; color:#ffffff;">fdasdfasf</span></p></body></html>',
            )
        )
        self.btn7.setText(_translate("MainWindow", "7"))
        self.btn8.setToolTip(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><span style=" font-weight:600; font-style:italic; text-decoration: underline; color:#ffffff;">fdasdfasf</span></p></body></html>',
            )
        )
        self.btn8.setText(_translate("MainWindow", "8"))
        self.btn_div.setToolTip(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><span style=" font-weight:600; font-style:italic; text-decoration: underline; color:#ffffff;">fdasdfasf</span></p></body></html>',
            )
        )
        self.btn_div.setText(_translate("MainWindow", "/"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
